title: "Review on Software"
author: "Seungkeun Lee"
description: ""
permalink: /:title/
lang: "ko"
excerpt_separator: "\n\n\n"
date_format: "%Y %B %d"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}
  - {title: "Archive", file: "archive.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:sngn.lee@samsung.com"}
  - {title: Github, icon: github, url: "https://github.com/myroot"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
  disqus_shortname: "sngnlee"    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed


defaults:
 - scope:
   path: "assets/images"
   values:
   image: true

